### ISSUE TITLE
Why do we need this ?

### ISSUE THREAD

**Issue by onlinebizsoft** [sansecio/corediff#17]
Every project is on git repository so we just need to run a composer reset whole source code and easily which files has changes in the repository.
Isnt it much more simple?

**Comment by gwillem** [comment]
Thanks for your solid question! You are correct, given an ideal (best practice) situation. In practice, we found that the sites that we need a verdict on, are generally messy and a composer reset isn't possible:

- Missing auth info for private packages
- Missing packages at upstream altogether
- Manually modified composer.lock

Maybe we could have solved this problem by extending composer to deal gracefully with upstream errors and just ignoring the broken/missing packages. But, as you can see, the corediff approach is very simple as well, covers missing packages, and has delivered good results for us so far.

**Comment by onlinebizsoft** [comment]
I got it. Thanks for the answer.

**Comment by danslo** [comment]
In addition to what @gwillem said, most automated deployments will strip files that are not necessary to run Magento in production. Things like the .git folder, composer.json, composer.lock, auth.json, etc.

This tool is primarily used in the context of investigating security incidents, and needs to work on as many installations as possible.
